# Generated by Django 6.0.3 on 2026-03-10 19:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nucleo', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='divida',
            name='valor',
        ),
        migrations.AddField(
            model_name='divida',
            name='ano_divida',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='divida',
            name='categoria_financeiro',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='divida',
            name='escola',
            field=models.CharField(choices=[('CNA VIVENDAS', 'CNA VIVENDAS'), ('CNA ITANHANGÁ', 'CNA ITANHANGÁ')], default='CNA VIVENDAS', max_length=50),
        ),
        migrations.AddField(
            model_name='divida',
            name='valor_atual',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='divida',
            name='valor_original',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='devedor',
            name='cpf',
            field=models.CharField(max_length=14, unique=True),
        ),
        migrations.AlterField(
            model_name='divida',
            name='devedor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dividas', to='nucleo.devedor'),
        ),
        migrations.AlterField(
            model_name='divida',
            name='parcela',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='divida',
            name='vencimento',
            field=models.DateField(blank=True, null=True),
        ),
    ]
