# Generated by Django 6.0.3 on 2026-03-12 12:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nucleo', '0002_remove_divida_valor_divida_ano_divida_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Acordo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_acordo', models.DateTimeField(auto_now_add=True)),
                ('valor_total', models.DecimalField(decimal_places=2, max_digits=12)),
                ('entrada', models.DecimalField(decimal_places=2, max_digits=12)),
                ('saldo', models.DecimalField(decimal_places=2, max_digits=12)),
                ('parcelas', models.IntegerField()),
                ('valor_parcela', models.DecimalField(decimal_places=2, max_digits=12)),
                ('devedor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nucleo.devedor')),
            ],
        ),
    ]
