# Generated by Django 6.0.3 on 2026-03-12 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nucleo', '0003_acordo'),
    ]

    operations = [
        migrations.AddField(
            model_name='acordo',
            name='numero_acordo',
            field=models.IntegerField(blank=True, null=True, unique=True),
        ),
    ]
