# Generated by Django 6.0.3 on 2026-03-12 23:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nucleo', '0004_acordo_numero_acordo'),
    ]

    operations = [
        migrations.AddField(
            model_name='acordo',
            name='status',
            field=models.CharField(choices=[('EM_NEGOCIACAO', 'Em Negociação'), ('AGUARDANDO_PAGAMENTO', 'Aguardando Pagamento'), ('PAGO', 'Pago'), ('QUEBRADO', 'Quebrado'), ('CANCELADO', 'Cancelado')], default='AGUARDANDO_PAGAMENTO', max_length=30),
        ),
    ]
