# Generated by Django 6.0.3 on 2026-03-13 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nucleo', '0005_acordo_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='RegraCobranca',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('modalidade', models.CharField(choices=[('DIRETA_CNA', 'Cobrança Direta CNA'), ('SERASA', 'Cobrança Serasa'), ('FEIRAO_SERASA', 'Cobrança Feirão Serasa')], max_length=30, unique=True)),
                ('limite_desconto_juros_multa', models.DecimalField(decimal_places=2, help_text='Percentual máximo de desconto permitido nos encargos', max_digits=5)),
                ('percentual_entrada_minima', models.DecimalField(decimal_places=2, help_text='Percentual mínimo de entrada exigido', max_digits=5)),
                ('parcelas_maximas', models.IntegerField()),
                ('ativa', models.BooleanField(default=True)),
            ],
        ),
        migrations.AddField(
            model_name='acordo',
            name='modalidade',
            field=models.CharField(blank=True, choices=[('DIRETA_CNA', 'Cobrança Direta CNA'), ('SERASA', 'Cobrança Serasa'), ('FEIRAO_SERASA', 'Cobrança Feirão Serasa')], max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='acordo',
            name='regra_snapshot_metadata',
            field=models.JSONField(blank=True, help_text='Cópia dos limites da RegraCobranca no momento da assinatura', null=True),
        ),
        migrations.AddField(
            model_name='acordo',
            name='valor_desconto_total',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='divida',
            name='modalidade_sugerida',
            field=models.CharField(blank=True, choices=[('DIRETA_CNA', 'Cobrança Direta CNA'), ('SERASA', 'Cobrança Serasa'), ('FEIRAO_SERASA', 'Cobrança Feirão Serasa')], help_text='Modalidade sugerida na importação (Colunas 21-40)', max_length=30, null=True),
        ),
    ]
