# Generated by Django 6.0.3 on 2026-03-13 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nucleo', '0006_regracobranca_acordo_modalidade_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='regracobranca',
            name='dias_atraso_minimo',
            field=models.IntegerField(default=0, help_text='Quantidade mínima de dias de atraso para esta regra'),
        ),
        migrations.AlterField(
            model_name='regracobranca',
            name='modalidade',
            field=models.CharField(choices=[('DIRETA_CNA', 'Cobrança Direta CNA'), ('SERASA', 'Cobrança Serasa'), ('FEIRAO_SERASA', 'Cobrança Feirão Serasa')], max_length=30),
        ),
    ]
