# Generated by Django 6.0.3 on 2026-03-13 22:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nucleo', '0007_regracobranca_dias_atraso_minimo_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Parcela',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.IntegerField(help_text='Número da parcela (0 para entrada)')),
                ('vencimento', models.DateField()),
                ('valor_previsto', models.DecimalField(decimal_places=2, max_digits=12)),
                ('valor_pago', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('data_pagamento', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('PENDENTE', 'Pendente'), ('PAGO', 'Pago'), ('ATRASADO', 'Atrasado')], default='PENDENTE', max_length=20)),
                ('acordo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalhe_parcelas', to='nucleo.acordo')),
            ],
            options={
                'ordering': ['numero'],
            },
        ),
    ]
