# Generated by Django 6.0.3 on 2026-03-15 15:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nucleo', '0009_devedor_bairro_devedor_celular_devedor_cep_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RegraNotificacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('slug', models.SlugField(unique=True)),
                ('ativo', models.BooleanField(default=True)),
                ('canal', models.CharField(choices=[('EMAIL', 'E-mail'), ('WHATSAPP', 'WhatsApp (Mock/Simulação)')], default='EMAIL', max_length=20)),
                ('status_alvo', models.CharField(choices=[('EM_NEGOCIACAO', 'Em Negociação'), ('AGUARDANDO_PAGAMENTO', 'Aguardando Pagamento'), ('PAGO', 'Pago'), ('QUEBRADO', 'Quebrado'), ('CANCELADO', 'Cancelado')], max_length=30)),
                ('dias_gatilho', models.IntegerField(help_text='Dias após a criação do acordo para disparar')),
                ('assunto_email', models.CharField(blank=True, max_length=200, null=True)),
                ('corpo_template', models.TextField(help_text='Placeholders: {nome}, {acordo_id}, {valor}, {escola}')),
            ],
        ),
        migrations.CreateModel(
            name='RegistroAuditoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_hora', models.DateTimeField(auto_now_add=True)),
                ('acao', models.CharField(choices=[('LOGIN', 'Login no Sistema'), ('LOGOUT', 'Logout do Sistema'), ('ACORDO_CRIADO', 'Acordo Criado'), ('ACORDO_STATUS', 'Mudança Status Acordo'), ('NOTIFICACAO_ENVIADA', 'Notificação de Cobrança Enviada'), ('NOTIFICACAO_FALHA', 'Falha no Envio de Notificação'), ('BAIXA_PARCELA', 'Baixa de Parcela Manual')], max_length=50)),
                ('detalhes', models.TextField()),
                ('registro_id', models.CharField(blank=True, help_text='ID do objeto afetado (ex: Acordo ID)', max_length=50, null=True)),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='HistoricoNotificacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_envio', models.DateTimeField(auto_now_add=True)),
                ('canal', models.CharField(max_length=20)),
                ('destinatario', models.CharField(max_length=255)),
                ('conteudo_enviado', models.TextField()),
                ('status', models.CharField(choices=[('SUCESSO', 'Sucesso'), ('ERRO', 'Erro'), ('SIMULADO', 'Simulado (Mock)')], max_length=20)),
                ('erro_log', models.TextField(blank=True, null=True)),
                ('acordo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notificacoes', to='nucleo.acordo')),
                ('regra', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='nucleo.regranotificacao')),
            ],
        ),
    ]
