# Generated by Django 6.0.3 on 2026-03-15 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nucleo', '0010_regranotificacao_registroauditoria_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registroauditoria',
            name='acao',
            field=models.CharField(choices=[('LOGIN', 'Login no Sistema'), ('LOGOUT', 'Logout do Sistema'), ('ACORDO_CRIADO', 'Acordo Criado'), ('ACORDO_STATUS', 'Mudança Status Acordo'), ('NOTIFICACAO_ENVIADA', 'Notificação de Cobrança Enviada'), ('NOTIFICACAO_FALHA', 'Falha no Envio de Notificação'), ('BAIXA_PARCELA', 'Baixa de Parcela Manual'), ('RELATORIO_GERADO', 'Relatório Gerado/Exportado')], max_length=50),
        ),
    ]
