# Generated by Django 6.0.3 on 2026-03-15 21:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nucleo', '0011_alter_registroauditoria_acao'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='registroauditoria',
            name='acao',
            field=models.CharField(choices=[('LOGIN', 'Login no Sistema'), ('LOGOUT', 'Logout do Sistema'), ('ACORDO_CRIADO', 'Acordo Criado'), ('ACORDO_STATUS', 'Mudança Status Acordo'), ('NOTIFICACAO_ENVIADA', 'Notificação de Cobrança Enviada'), ('NOTIFICACAO_FALHA', 'Falha no Envio de Notificação'), ('BAIXA_PARCELA', 'Baixa de Parcela Manual'), ('RELATORIO_GERADO', 'Relatório Gerado/Exportado'), ('RETORNO_IMPORTADO', 'Lote de Pagamentos Importado'), ('PAGAMENTO_MANUAL', 'Reconciliação Manual de Pagamento')], max_length=50),
        ),
        migrations.CreateModel(
            name='LoteRetornoPagamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('arquivo', models.FileField(upload_to='retornos_pagamento/')),
                ('data_importacao', models.DateTimeField(auto_now_add=True)),
                ('qtd_linhas_total', models.IntegerField(default=0)),
                ('qtd_sucesso_auto', models.IntegerField(default=0)),
                ('qtd_pendentes_revisar', models.IntegerField(default=0)),
                ('qtd_falhas_fatais', models.IntegerField(default=0)),
                ('status_processamento', models.CharField(choices=[('PROCESSANDO', 'Processando'), ('CONCLUIDO', 'Concluido'), ('AGUARDANDO_REVISAO', 'Aguardando Revisão Manual')], default='PROCESSANDO', max_length=20)),
                ('operador', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lotes_retorno', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ItemRetornoPendente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('raw_cpf', models.CharField(blank=True, max_length=14, null=True)),
                ('raw_acordo_id', models.CharField(blank=True, max_length=20, null=True)),
                ('raw_valor', models.CharField(blank=True, max_length=50, null=True)),
                ('raw_data', models.CharField(blank=True, max_length=50, null=True)),
                ('motivo_pendencia', models.TextField()),
                ('resolvido', models.BooleanField(default=False)),
                ('data_resolucao', models.DateTimeField(blank=True, null=True)),
                ('acordo_vinculado_manual', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='itens_retorno_resolvidos', to='nucleo.acordo')),
                ('operador_resolucao', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('lote', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itens_pendentes', to='nucleo.loteretornopagamento')),
            ],
        ),
        migrations.CreateModel(
            name='PagamentoAcordo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_pagamento', models.DateField(db_index=True)),
                ('valor_pago', models.DecimalField(decimal_places=2, max_digits=10)),
                ('meio_pagamento', models.CharField(blank=True, max_length=50, null=True)),
                ('referencia_externa', models.CharField(blank=True, max_length=100, null=True)),
                ('reconciliado_manualmente', models.BooleanField(default=False)),
                ('data_registro', models.DateTimeField(auto_now_add=True)),
                ('acordo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pagamentos_detalhados', to='nucleo.acordo')),
                ('lote', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pagamentos_gerados', to='nucleo.loteretornopagamento')),
            ],
        ),
    ]
