# Generated by Django 6.0.3 on 2026-03-17 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nucleo', '0012_alter_registroauditoria_acao_loteretornopagamento_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='loteretornopagamento',
            name='arquivo_hash',
            field=models.CharField(blank=True, help_text='Hash SHA256 do arquivo para evitar duplicatas', max_length=64, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='pagamentoacordo',
            name='referencia_externa',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
    ]
