# Generated by Django 6.0.3 on 2026-03-17 13:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nucleo', '0014_acordo_usuario_criador_pagamentoacordo_operador'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='registroauditoria',
            name='acao',
            field=models.CharField(choices=[('LOGIN', 'Login no Sistema'), ('LOGOUT', 'Logout do Sistema'), ('ACORDO_CRIADO', 'Acordo Criado'), ('ACORDO_STATUS', 'Mudança Status Acordo'), ('NOTIFICACAO_ENVIADA', 'Notificação de Cobrança Enviada'), ('NOTIFICACAO_FALHA', 'Falha no Envio de Notificação'), ('BAIXA_PARCELA', 'Baixa de Parcela Manual'), ('RELATORIO_GERADO', 'Relatório Gerado/Exportado'), ('RETORNO_IMPORTADO', 'Lote de Pagamentos Importado'), ('PAGAMENTO_MANUAL', 'Reconciliação Manual de Pagamento'), ('ALERTA_GERADO', 'Alerta Financeiro Gerado pelo Sistema')], max_length=50),
        ),
        migrations.CreateModel(
            name='AlertaFinanceiro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_alerta', models.CharField(choices=[('PARCELA_ATRASADA', 'Parcela Atrasada'), ('ACORDO_RISCO', 'Acordo em Risco (Atraso Significativo)'), ('QUEBRA_ACORDO', 'Quebra de Acordo Detectada'), ('RISCO_PROXIMO', 'Risco: Vencimento Próximo')], max_length=50)),
                ('severidade', models.CharField(choices=[('BAIXA', 'Baixa'), ('MEDIA', 'Média'), ('ALTA', 'Alta')], default='BAIXA', max_length=20)),
                ('status', models.CharField(choices=[('ABERTO', 'Aberto'), ('RESOLVIDO', 'Resolvido'), ('IGNORADO', 'Ignorado')], default='ABERTO', max_length=20)),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
                ('descricao', models.TextField()),
                ('origem', models.CharField(default='SISTEMA', max_length=20)),
                ('acordo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alertas', to='nucleo.acordo')),
                ('parcela', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='alertas', to='nucleo.parcela')),
                ('usuario_responsavel', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Alerta Financeiro',
                'verbose_name_plural': 'Alertas Financeiros',
            },
        ),
    ]
