# Generated by Django 6.0.3 on 2026-03-17 13:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nucleo', '0015_alter_registroauditoria_acao_alertafinanceiro'),
    ]

    operations = [
        migrations.AddField(
            model_name='historiconotificacao',
            name='alerta',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notificacoes_vinculadas', to='nucleo.alertafinanceiro'),
        ),
    ]
