# Generated by Django 6.0.3 on 2026-03-17 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nucleo', '0016_historiconotificacao_alerta'),
    ]

    operations = [
        migrations.AddField(
            model_name='historiconotificacao',
            name='data_entrega',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='historiconotificacao',
            name='data_leitura',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='historiconotificacao',
            name='mensagem_id_externo',
            field=models.CharField(blank=True, db_index=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='alertafinanceiro',
            name='status',
            field=models.CharField(choices=[('ABERTO', 'Aberto'), ('EM_TRATAMENTO', 'Em Tratamento (Lido/Em Contato)'), ('RESOLVIDO', 'Resolvido'), ('IGNORADO', 'Ignorado')], default='ABERTO', max_length=20),
        ),
        migrations.AlterField(
            model_name='historiconotificacao',
            name='status',
            field=models.CharField(choices=[('PENDENTE', 'Pendente'), ('ENVIADO', 'Enviado'), ('ENTREGUE', 'Entregue'), ('LIDO', 'Lido'), ('FALHA', 'Falha'), ('SIMULADO', 'Simulado (Mock)')], max_length=20),
        ),
    ]
