# Generated by Django 6.0.3 on 2026-03-17 14:07

import uuid
from django.db import migrations, models


def gen_uuid(apps, schema_editor):
    Devedor = apps.get_model('nucleo', 'Devedor')
    for row in Devedor.objects.all():
        row.uuid_acesso = uuid.uuid4()
        row.save()

class Migration(migrations.Migration):

    dependencies = [
        ('nucleo', '0017_historiconotificacao_data_entrega_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='devedor',
            name='uuid_acesso',
            field=models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, null=True),
        ),
        migrations.RunPython(gen_uuid, reverse_code=migrations.RunPython.noop),
        migrations.AlterField(
            model_name='devedor',
            name='uuid_acesso',
            field=models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True),
        ),
        migrations.AlterField(
            model_name='registroauditoria',
            name='acao',
            field=models.CharField(choices=[('LOGIN', 'Login no Sistema'), ('LOGOUT', 'Logout do Sistema'), ('ACORDO_CRIADO', 'Acordo Criado'), ('ACORDO_STATUS', 'Mudança Status Acordo'), ('NOTIFICACAO_ENVIADA', 'Notificação de Cobrança Enviada'), ('NOTIFICACAO_FALHA', 'Falha no Envio de Notificação'), ('BAIXA_PARCELA', 'Baixa de Parcela Manual'), ('RELATORIO_GERADO', 'Relatório Gerado/Exportado'), ('RETORNO_IMPORTADO', 'Lote de Pagamentos Importado'), ('PAGAMENTO_MANUAL', 'Reconciliação Manual de Pagamento'), ('ALERTA_GERADO', 'Alerta Financeiro Gerado pelo Sistema'), ('ALERTA_ATUALIZADO', 'Alerta Financeiro Atualizado'), ('ALERTA_RESOLVIDO', 'Alerta Financeiro Resolvido'), ('PORTAL_ACESSO', 'Acesso ao Portal do Devedor')], max_length=50),
        ),
    ]
